title: Thomas Bidne
email: tbidne@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ''
url: ''
github_username: tbidne
github:
  username: tbidne

lang: en

social:
  name: Thomas Bidne
  email: tbidne@gmail.com
  links:
    - https://github.com/tbidne
    - https://www.linkedin.com/in/tbidne

# Build settings
markdown: kramdown
theme:
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass

collections:
  tabs:
    output: true
    sort_by: order

toc: true

defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: false
      toc: true
      permalink: /posts/:title/
  - scope:
      path: ''
      type: tabs
    values:
      layout: default
      # Maps /_tabs/t to /t
      permalink: /:title/

assets:
  self_host:
    enabled: false
    env: # [development|production]

theme_mode: # [dark | light]
avatar: '/assets/img/avatar.png'

paginate: 5

projects:
  apps:
    - title: Shrun
      gh-repo: shrun
      desc: A tool for running and timing multiple shell commands concurrently.

    - title: Navi
      gh-repo: navi
      desc: A tool for easily creating desktop notifications for arbitrary actions.

    - title: Safe rm
      gh-repo: safe-rm
      desc: A safer alternative to the venerable unix tool 'rm'.

    - title: Time Conv
      gh-repo: time-conv
      desc: CLI tool for easy timezone conversion.
  libs:
    - title: Algebra Simple
      gh-repo: algebra-simple
      desc: A safe and more cohesive alternative to Haskell's default algebraic
        representation, taking inspiration from abstract algebra.

    - title: SI Bytes
      gh-repo: si-bytes
      desc: Haskell library for type-safe byte operations i.e. ensures that
        byte sizes are handled correctly.

    - title: Monad Effects
      gh-repo: monad-effects
      desc: Haskell library for "effectful" programming based on the Monad
        typeclass.

    - title: Nix Hs Shells
      gh-repo: nix-hs-shells
      desc: Nix shells for Haskell development.

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
