name: style

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0

      - name: Setup nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/b39924fc7764c08ae3b51beef9a3518c414cdb7d.tar.gz
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Format
        run: nix develop -c bash -c "npm install && npm run fmtc"

      - name: Lint
        run: nix develop -c bash -c "npm install && npm run lintc_css"
